// import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import { Toaster } from "react-hot-toast";

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//         <Toaster
//           toastOptions={{
//             duration: 3000,
//           }}
//         />
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }


'use client';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from "react-hot-toast";
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  useEffect(() => {
    // Initialize toaster in the effect
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster
          toastOptions={{
            duration: 3000,
          }}
        />
      </body>
    </html>
  )
}
